version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_env2451713Project
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: bvt
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SSL_JDBC_Test
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: JMS2waySSL
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_env2451713.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_env2451713Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_env2451713.integrations:Sum
  packages:
  - name: SIQA_env2451713Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_env2451713.integrations:deepclonetest
  packages:
  - name: SIQA_env2451713Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: project.siqa_env2451713.integrations:tppdaf
  packages:
  - name: SIQA_env2451713Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
